services:
  - type: web
    name: hijack-detection-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        # We will set this in the Render dashboard
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
